services:
  toolkit-venv:
    build: .
    working_dir: /opt/project
    environment:
      - PYTHONPATH=/opt/project/src
      - TWINE_USERNAME=${TWINE_USERNAME}
      - TWINE_PASSWORD=${TWINE_PASSWORD}
    volumes:
      - .:/opt/project
    command: >
      sh -c "
        # Remove BOM se houver
        sed -i '1s/^\xEF\xBB\xBF//' pyproject.toml &&
        pip install --upgrade build twine &&
        python -m build &&
        twine upload --non-interactive dist/* &&
        sleep infinity
      "
    healthcheck:
      test: ["CMD", "python", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
